### ISSUE TITLE
errror

### ISSUE THREAD

**Issue by Olivine997** [jukworks/swat-seq2seq#2]
Hello, how can I solve this problem? Thanks.

        - fetched 1,000 datapoints
	- fetched 1,000 datapoints
	- fetched 1,000 datapoints
	- fetched 1,000 datapoints
* 2015-12-30 19:00:00
	- fetched 1,000 datapoints
	- fetched 1,000 datapoints
	- fetched 1,000 datapoints
	- fetched 1,000 datapoints
* 2016-01-02 04:00:00
	- fetched 1,000 datapoints
Traceback (most recent call last):
  File "judge.py", line 50, in push
    self.bucket.append(self.buffer.popleft())
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "judge.py", line 123, in <module>
    main()
  File "judge.py", line 119, in main
    judge.push()
  File "judge.py", line 53, in push
    self.fetch_to_buffer()
  File "judge.py", line 33, in fetch_to_buffer
    for s in statement['series']:
KeyError: 'series'

**Comment by lcthe** [comment]
I have the same problem, have you solved it now?
